const STORAGE_KEY = 'btrtAwardsMockSubmissionsV1';
const JUDGE_KEY = 'btrtAwardsMockJudgeScoresV1';
const assessmentCriteria = [
  { key:'values', label:'Values Demonstration', weight:40 },
  { key:'impact', label:'Impact (Business + People)', weight:30 },
  { key:'scale', label:'Scale & Influence', weight:10 },
  { key:'difficulty', label:'Difficulty & Context', weight:10 },
  { key:'story', label:'Story & Replicability', weight:10 }
];
const judgeCriteria = [
  { key:'alignment', label:'BTRT Value Alignment', weight:30 },
  { key:'impact', label:'Impact', weight:30 },
  { key:'roleModel', label:'Role Model Quality', weight:25 },
  { key:'distinctiveness', label:'Distinctiveness', weight:15 }
];
function $(id){ return document.getElementById(id); }
function data(){ return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); }
function saveData(rows){ localStorage.setItem(STORAGE_KEY, JSON.stringify(rows)); }
function judgeData(){ return JSON.parse(localStorage.getItem(JUDGE_KEY) || '{}'); }
function saveJudgeData(rows){ localStorage.setItem(JUDGE_KEY, JSON.stringify(rows)); }
function toast(msg){ const el=$('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2800); }
function uid(prefix='BTRT'){ return `${prefix}-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`; }
function formValues(form){ const fd = new FormData(form); const obj = {}; fd.forEach((value,key)=>{ if(obj[key]){ if(!Array.isArray(obj[key])) obj[key]=[obj[key]]; obj[key].push(value); } else obj[key]=value; }); form.querySelectorAll('input[type=checkbox]').forEach(cb=>{ if(!obj[cb.name]) obj[cb.name]=[]; }); return obj; }
function checkedValues(form, name){ return [...form.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value); }
function weightedScore(criteria, obj, prefix='rating_'){ return Math.round(criteria.reduce((sum,c)=>sum + ((Number(obj[prefix+c.key]) || 0) * c.weight / 5), 0)); }
function storyFromCompany(o){ return [o.situation1,o.task1,o.action1,o.result1].filter(Boolean).join(' '); }
function snapshot(text){ return (text || '').replace(/\s+/g,' ').trim().slice(0,180) + ((text||'').length>180 ? '…' : ''); }
function setToday(){ const d = new Date().toISOString().slice(0,10); document.querySelectorAll('input[type=date]').forEach(i=>{ if(!i.value) i.value=d; }); }
function initTabs(){ document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{ document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); $(btn.dataset.tab).classList.add('active'); renderAll(); })); }
function initCounters(){ document.querySelectorAll('textarea[data-counter]').forEach(t=>t.addEventListener('input',()=>$(t.dataset.counter).textContent=t.value.length)); }
function renderAssessmentRows(){ $('assessmentRows').innerHTML = assessmentCriteria.map(c=>`<tr><td><strong>${c.label}</strong></td><td>${c.weight}%</td><td><input type="number" min="1" max="5" name="rating_${c.key}" data-company-score required /></td><td><textarea rows="2" name="justify_${c.key}" placeholder="Brief justification"></textarea></td></tr>`).join(''); document.querySelectorAll('[data-company-score]').forEach(i=>i.addEventListener('input', updateCompanyScore)); }
function updateCompanyScore(){ const form=$('companyForm'); const obj=formValues(form); $('companyWeightedScore').textContent = weightedScore(assessmentCriteria,obj); }
function renderJudgeScoreRows(){ $('judgeScoreRows').innerHTML = judgeCriteria.map(c=>`<div class="score-row"><label>${c.label} <small>${c.weight}%</small><input type="range" min="1" max="5" value="3" name="j_${c.key}" data-judge-score /><small>Rating: <span id="jv_${c.key}">3</span>/5</small></label></div>`).join(''); document.querySelectorAll('[data-judge-score]').forEach(i=>i.addEventListener('input', updateJudgePreview)); updateJudgePreview(); }
function updateJudgePreview(){ let score=0; judgeCriteria.forEach(c=>{ const val=Number(document.querySelector(`[name="j_${c.key}"]`)?.value || 0); const span=$(`jv_${c.key}`); if(span) span.textContent=val; score += val*c.weight/5; }); $('judgeScorePreview').textContent = Math.round(score); }
function initForms(){ $('peerForm').addEventListener('submit', e=>{ e.preventDefault(); const f=e.currentTarget; if(!checkedValues(f,'values').length) return toast('Select at least one YTL Core Value.'); const o=formValues(f); o.values=checkedValues(f,'values'); const row={ id:uid('PEER'), type:'Peer Nomination', status:'Peer Submitted', createdAt:new Date().toISOString(), nomineeName:o.nomineeName, companyDept:o.companyDept, values:o.values, score:'', story:o.story, raw:o }; const rows=data(); rows.unshift(row); saveData(rows); f.reset(); $('peerStoryCount').textContent='0'; toast('Peer nomination submitted. It is now visible in HR / HOD Dashboard.'); renderAll(); });
$('companyForm').addEventListener('submit', e=>{ e.preventDefault(); const f=e.currentTarget; if(!checkedValues(f,'values1').length) return toast('Evidence 1 needs at least one YTL Core Value.'); const o=formValues(f); o.values1=checkedValues(f,'values1'); o.values2=checkedValues(f,'values2'); o.docs=checkedValues(f,'docs'); const score=weightedScore(assessmentCriteria,o); const row={ id:uid('OFFICIAL'), type:'Official Company Package', status:o.directorApproval==='Yes'?'Validated':'Needs Detail', createdAt:new Date().toISOString(), nomineeName:o.nomineeName, companyDept:`${o.company} / ${o.department}`, values:[...new Set([...(o.values1||[]),...(o.values2||[])])], score, story:storyFromCompany(o), raw:o }; const rows=data(); rows.unshift(row); saveData(rows); f.reset(); setToday(); updateCompanyScore(); toast('Official company package submitted.'); renderAll(); });
$('judgeForm').addEventListener('submit', e=>{ e.preventDefault(); const id=$('judgeSelect').value; if(!id) return toast('Select a finalist first.'); const scores=judgeData(); const fd=formValues(e.currentTarget); const total=Math.round(judgeCriteria.reduce((s,c)=>s+(Number(fd['j_'+c.key]||0)*c.weight/5),0)); scores[id]={ total, notes:fd.judgeNotes || '', scores:fd, updatedAt:new Date().toISOString() }; saveJudgeData(scores); toast('Judge score saved.'); renderAll(); });
}
function initButtons(){ $('loadExamplePeer').addEventListener('click',()=>{ const f=$('peerForm'); f.nominatorName.value='Alicia Wong'; f.nominatorEmail.value='alicia.wong@example.com'; f.nomineeName.value='Sarah Lim'; f.nomineeEmail.value='sarah.lim@example.com'; f.companyDept.value='YTL Creative Communications / Brand'; f.relationship.value='Project Stakeholder'; f.querySelector('input[value="Togetherness"]').checked=true; f.querySelector('input[value="Hard Work"]').checked=true; f.story.value='During a tight internal campaign rollout, Sarah noticed that several teams were unclear about the final approval flow. She created a simple tracker, clarified owners, followed up with each stakeholder and helped the team submit all materials before the deadline with fewer last-minute corrections.'; f.benefit.value='Brand team, Comms stakeholders and campaign approvers'; $('peerStoryCount').textContent=f.story.value.length; });
$('loadExampleCompany').addEventListener('click', loadCompanyExample); $('prefillFromPeer').addEventListener('click', prefillLatestPeer); $('exportJson').addEventListener('click', exportJson); $('exportCsv').addEventListener('click', exportCsv); $('resetData').addEventListener('click',()=>{ if(confirm('Reset all local mock submissions and judge scores?')){ localStorage.removeItem(STORAGE_KEY); localStorage.removeItem(JUDGE_KEY); seedIfEmpty(true); renderAll(); toast('Demo data reset.'); } }); $('searchBox').addEventListener('input', renderDashboard); $('statusFilter').addEventListener('change', renderDashboard); }
function loadCompanyExample(){ const f=$('companyForm'); f.company.value='YTL Creative Communications'; f.submissionDate.value=new Date().toISOString().slice(0,10); f.directorName.value='Demo Director'; f.directorDesignation.value='Director, Creative Communications'; f.pic.value='HR Comms PIC, hrcomms@example.com'; f.nomineeName.value='Sarah Lim'; f.employeeId.value='YTL-2026-001'; f.jobTitle.value='Senior Executive'; f.department.value='Brand'; f.years.value='4'; f.manager.value='Demo Manager'; f.location.value='Kuala Lumpur, Malaysia'; f.hodName.value='Demo HOD'; f.hodDesignation.value='Head of Brand'; f.relationship.value='Functional Head'; f.internalDate.value=new Date().toISOString().slice(0,10); f.directorApproval.value='Yes'; ['Hard Work','Togetherness'].forEach(v=>{ const cb=[...f.querySelectorAll('input[name="values1"]')].find(x=>x.value===v); if(cb) cb.checked=true; }); f.situation1.value='The team had to deliver a Group-wide internal campaign under a compressed timeline with multiple stakeholders, unclear inputs and changing approval requirements.'; f.task1.value='The nominee was responsible for coordinating submission readiness, aligning stakeholders and ensuring campaign materials moved through approval without missing the launch date.'; f.action1.value='She built a live tracker, clarified ownership, followed up with stakeholders, prepared concise status updates and supported junior team members who were unfamiliar with the approval flow.'; f.result1.value='The campaign materials were submitted before deadline, the number of repeated corrections reduced, and stakeholders had a clearer view of ownership and next steps.'; ['values','impact','scale','difficulty','story'].forEach((k,i)=>{ f[`rating_${k}`].value=[5,4,4,4,5][i]; f[`justify_${k}`].value='Clear evidence with practical impact and behaviour that can be replicated by others.'; }); f.querySelector('input[value="Completed nomination form"]').checked=true; f.querySelector('input[value="Peer nomination letters or endorsements"]').checked=true; f.querySelector('input[value="Project reports or data outputs"]').checked=true; f.attachmentNotes.value='Demo tracker screenshot, peer nomination summary, approval timeline.'; updateCompanyScore(); toast('Example loaded. Review and submit it.'); }
function prefillLatestPeer(){ const peer=data().find(x=>x.type==='Peer Nomination'); if(!peer) return toast('No peer nomination found yet. Submit one first or load example.'); const f=$('companyForm'); f.company.value=(peer.raw.companyDept || '').split('/')[0].trim(); f.nomineeName.value=peer.nomineeName; f.department.value=peer.raw.companyDept || ''; f.relationship.value=peer.raw.relationship || ''; f.hodName.value=peer.raw.nominatorName || ''; f.situation1.value='Peer nomination received. HR / HOD to validate the situation and supporting evidence.'; f.action1.value=peer.story || ''; peer.values.forEach(v=>{ const cb=[...f.querySelectorAll('input[name="values1"]')].find(x=>x.value===v); if(cb) cb.checked=true; }); toast('Latest peer nomination copied into the official package draft.'); document.querySelector('[data-tab="company"]').click(); }
function renderDashboard(){ const q=($('searchBox').value||'').toLowerCase(); const sf=$('statusFilter').value; const rows=data().filter(r=>{ const hay=[r.id,r.nomineeName,r.companyDept,(r.values||[]).join(' '),r.type,r.status].join(' ').toLowerCase(); return (!q||hay.includes(q)) && (!sf||r.status===sf); }); $('dashboardRows').innerHTML = rows.map(r=>`<tr><td>${r.id}</td><td><strong>${r.nomineeName||'-'}</strong><br><small>${new Date(r.createdAt).toLocaleString()}</small></td><td>${r.companyDept||'-'}</td><td>${(r.values||[]).map(v=>`<span class="status-pill">${v}</span>`).join(' ')}</td><td>${r.type}</td><td>${r.score || '-'}</td><td><select data-status="${r.id}">${['Peer Submitted','Needs Detail','Validated','Shortlisted','Finalist','Not Selected'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="secondary" data-review="${r.id}">Review</button></td></tr>`).join('') || '<tr><td colspan="8">No submissions yet.</td></tr>'; document.querySelectorAll('[data-status]').forEach(sel=>sel.addEventListener('change',()=>{ const rows=data(); const r=rows.find(x=>x.id===sel.dataset.status); if(r){ r.status=sel.value; saveData(rows); toast('Status updated.'); renderAll(); } })); document.querySelectorAll('[data-review]').forEach(btn=>btn.addEventListener('click',()=>showReview(btn.dataset.review))); }
function showReview(id){ const r=data().find(x=>x.id===id); if(!r) return; const panel=$('reviewPanel'); panel.classList.remove('hidden'); panel.innerHTML=`<h3>Review Nominee: ${r.nomineeName}</h3><p><strong>Status:</strong> ${r.status} &nbsp; <strong>Type:</strong> ${r.type} &nbsp; <strong>Score:</strong> ${r.score || '-'}</p><p><strong>Values:</strong> ${(r.values||[]).join(', ') || '-'}</p><p><strong>Evidence snapshot:</strong> ${snapshot(r.story)}</p><details open><summary>Full captured data</summary><pre>${escapeHtml(JSON.stringify(r.raw,null,2))}</pre></details>`; panel.scrollIntoView({behavior:'smooth',block:'nearest'}); }
function renderJudges(){ const finalists=data().filter(r=>r.status==='Finalist'); $('judgeSelect').innerHTML = finalists.length ? finalists.map(r=>`<option value="${r.id}">${r.nomineeName} — ${r.companyDept}</option>`).join('') : '<option value="">No finalists yet</option>'; renderDossier(); const scores=judgeData(); const ranked=[...finalists].sort((a,b)=>(scores[b.id]?.total||0)-(scores[a.id]?.total||0)); $('finalistRows').innerHTML = ranked.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${r.nomineeName}</strong><br><small>${r.companyDept}</small></td><td>${(r.values||[]).join(', ')}</td><td>${snapshot(r.story)}</td><td>${r.score || '-'}</td><td>${scores[r.id]?.total || '-'}</td><td>${scores[r.id]?.notes || '-'}</td></tr>`).join('') || '<tr><td colspan="7">No finalists yet. Mark a nominee as Finalist in the HR / HOD Dashboard.</td></tr>'; }
function renderDossier(){ const id=$('judgeSelect').value; const r=data().find(x=>x.id===id); $('judgeDossier').innerHTML = r ? `<h3>${r.nomineeName}</h3><p><strong>Company / Dept:</strong> ${r.companyDept}</p><p><strong>Values:</strong> ${(r.values||[]).join(', ')}</p><p><strong>Company assessment score:</strong> ${r.score || '-'}</p><h4>S.T.A.R. Evidence Snapshot</h4><p>${snapshot(r.story)}</p><details><summary>Open full record</summary><pre>${escapeHtml(JSON.stringify(r.raw,null,2))}</pre></details>` : '<p>No finalist selected.</p>'; }
function renderAll(){ renderDashboard(); renderJudges(); }
function exportJson(){ const blob=new Blob([JSON.stringify({submissions:data(),judgeScores:judgeData()},null,2)],{type:'application/json'}); downloadBlob(blob,'btrt-mock-export.json'); }
function exportCsv(){ const rows=data(); const header=['id','type','status','createdAt','nomineeName','companyDept','values','score','story']; const csv=[header.join(',')].concat(rows.map(r=>header.map(h=>`"${String(Array.isArray(r[h])?r[h].join('; '):(r[h]??'')).replaceAll('"','""')}"`).join(','))).join('\n'); downloadBlob(new Blob([csv],{type:'text/csv'}),'btrt-mock-export.csv'); }
function downloadBlob(blob,name){ const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }
function escapeHtml(s){ return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function seedIfEmpty(force=false){ if(!force && data().length) return; const seed={ id:'OFFICIAL-2026-DEMO01', type:'Official Company Package', status:'Finalist', createdAt:new Date().toISOString(), nomineeName:'Sarah Lim', companyDept:'YTL Creative Communications / Brand', values:['Hard Work','Togetherness'], score:88, story:'The team had to deliver a Group-wide internal campaign under a compressed timeline. Sarah built a live tracker, clarified ownership, supported junior team members and reduced repeated corrections. The campaign materials were submitted before deadline and stakeholders had clearer visibility of next steps.', raw:{company:'YTL Creative Communications', nomineeName:'Sarah Lim', directorApproval:'Yes', situation1:'Compressed timeline with multiple stakeholders.', task1:'Coordinate readiness and approvals.', action1:'Built tracker, clarified owners and followed up.', result1:'Submitted before deadline with fewer corrections.'}}; saveData([seed]); saveJudgeData({}); }
document.addEventListener('DOMContentLoaded',()=>{ initTabs(); initCounters(); renderAssessmentRows(); renderJudgeScoreRows(); initForms(); initButtons(); $('judgeSelect').addEventListener('change',renderDossier); setToday(); seedIfEmpty(); renderAll(); });
